### ISSUE TITLE
Can't set user password in helpdesk module

### ISSUE THREAD

**Issue by garudaru** [pwm-project/pwm#266]
![pwm-helpdesk-changepassword](https://user-images.githubusercontent.com/5989693/34926141-73999f28-f9cf-11e7-9dce-12405302d660.PNG)

Button "Change password" is not activated
PWM v1.8.0-SNAPSHOT b31360855 
pwm-1.8.0-SNAPSHOT-2018-01-13T19:37:35Z-release-bundle.zip

**Comment by jrivard** [comment]
I beleive this is fixed in current bundles.

**Comment by chhayheng168** [comment]
I already met this issue and using latest version, but problem still exist.
